name:                servant-study
version:             0.1.0.0
github:              "githubuser/servant-study"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-study#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- text
- heftia-effects ^>= 0.5.0
- ghc-typelits-knownnat ^>= 0.7
- lens
- email-validate
- bytestring
- safe-exceptions
- persistent
- persistent-postgresql
- yaml
- monad-logger
- mtl
- polysemy
- polysemy-plugin
- req
- modern-uri
- string-interpolate

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin=Polysemy.Plugin

default-extensions:
- LambdaCase
- DerivingStrategies
- DataKinds
- TypeFamilies
- BlockArguments
- FunctionalDependencies
- RecordWildCards
- DefaultSignatures
- PatternSynonyms
- TemplateHaskell
- PartialTypeSignatures
- AllowAmbiguousTypes
- DuplicateRecordFields
- OverloadedRecordDot
- NoFieldSelectors
- OverloadedStrings

library:
  source-dirs: src
  language: GHC2021

executables:
  servant-study-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-study

tests:
  servant-study-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-study
    - hspec
    - hspec-wai
    - hspec-wai-json
    - QuickCheck
    - aeson
    - mockcat
