version: '3.8'

services:
  postgres:
    image: postgres:17.0-bullseye
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  wiremock:
    image: wiremock/wiremock:latest-alpine
    container_name: wiremock_mock
    restart: always
    ports:
      - "8080:8080"
